// script.js — core VibeFuse functionality (commit 2)
(() => {
  // DOM refs
  const moodInput = document.getElementById('mood');
  const generateBtn = document.getElementById('generate');
  const preview = document.getElementById('preview');
  const toggleAnimateBtn = document.getElementById('toggle-animate');
  const copyCssBtn = document.getElementById('copy-css');

  let animated = true;
  let current = null;

  // Simple deterministic hash -> seed
  function hashStringToSeed(str) {
    let h = 2166136261 >>> 0;
    for (let i = 0; i < str.length; i++) {
      h ^= str.charCodeAt(i);
      h = Math.imul(h, 16777619) >>> 0;
    }
    return h;
  }

  // seeded random generator (xorshift32-like)
  function seededRandom(seed) {
    let x = seed >>> 0;
    return function() {
      x ^= x << 13;
      x ^= x >>> 17;
      x ^= x << 5;
      return ((x >>> 0) / 4294967295);
    };
  }

  // generate two pleasing HSL colors from mood string
  function generateColorsFromMood(mood) {
    const seed = hashStringToSeed(mood.trim().toLowerCase() || 'neutral');
    const rnd = seededRandom(seed);
    // choose two hues, ensure distance for contrast
    const h1 = Math.floor(rnd() * 360);
    const h2 = (h1 + 120 + Math.floor(rnd() * 120)) % 360;
    // vary saturation/lightness for vibe
    const s1 = 55 + Math.floor(rnd() * 20); // 55-75
    const s2 = 45 + Math.floor(rnd() * 30); // 45-75
    const l1 = 40 + Math.floor(rnd() * 20); // 40-60
    const l2 = 35 + Math.floor(rnd() * 25); // 35-60
    return [
      `hsl(${h1} ${s1}% ${l1}%)`,
      `hsl(${h2} ${s2}% ${l2}%)`
    ];
  }

  // apply gradient to preview; if animated, create a subtle movement
  function applyGradient(colors, {animate = true} = {}) {
    const css = `background: linear-gradient(135deg, ${colors[0]}, ${colors[1]});`;
    preview.style.cssText = css + 'border-radius:10px;color:inherit;display:flex;align-items:center;justify-content:center;';
    preview.dataset.css = css;
    preview.textContent = ''; // we will show small label
    preview.style.position = 'relative';

    // remove any existing animation rules by clearing inline background size/position
    preview.style.backgroundSize = '';
    preview.style.animation = '';

    if (animate) {
      // subtle animated background-position using CSS animation
      preview.style.backgroundSize = '200% 200%';
      preview.style.animation = 'vibeShift 8s ease-in-out infinite';
      // ensure keyframes are present
      ensureKeyframes();
    }
  }

  // create or ensure keyframes exist for vibeShift
  function ensureKeyframes() {
    const name = 'vibeShift';
    const doc = document;
    const styleId = 'vibefuse-animations';
    let style = doc.getElementById(styleId);
    if (!style) {
      style = doc.createElement('style');
      style.id = styleId;
      style.textContent = `
@keyframes ${name} {
  0% { background-position: 0% 50%; }
  50% { background-position: 100% 50%; }
  100% { background-position: 0% 50%; }
}`;
      doc.head.appendChild(style);
    }
  }

  // UI actions
  function generateFromInput() {
    const mood = moodInput.value || '';
    const colors = generateColorsFromMood(mood);
    current = {mood, colors};
    applyGradient(colors, {animate});
    preview.textContent = mood ? mood.toUpperCase() : 'Vibe';
  }

  function toggleAnimate() {
    animated = !animated;
    if (current) applyGradient(current.colors, {animate: animated});
    toggleAnimateBtn.textContent = animated ? 'Toggle Animate' : 'Toggle Animate';
  }

  async function copyCssToClipboard() {
    const css = preview.dataset.css || '';
    const full = `${css}\n/* Generated by VibeFuse */`;
    try {
      await navigator.clipboard.writeText(full);
      copyCssBtn.textContent = 'Copied!';
      setTimeout(() => (copyCssBtn.textContent = 'Copy CSS'), 1400);
    } catch (e) {
      copyCssBtn.textContent = 'Copy Failed';
      setTimeout(() => (copyCssBtn.textContent = 'Copy CSS'), 1400);
    }
  }

  // wire events
  generateBtn.addEventListener('click', generateFromInput);
  toggleAnimateBtn.addEventListener('click', () => { toggleAnimate(); });
  copyCssBtn.addEventListener('click', copyCssToClipboard);

  // initial generate
  generateFromInput();
})();
